parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Sandbox\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Aws\DynamoDb\Marshaler:

    Aws\DynamoDb\DynamoDbClient:
        arguments:
            $args:
                region: eu-central-1
